version: prometheus/v1
service: prodTesting99999
labels:
  product_id: prodTesting99999
  env: dev
  org_id: Technology Services Engineering
slos:
  - name: prodTesting99999
    objective: 96
    description: prodTesting99999
    sli:
      events:
        error_query: prodTesting99999
        total_query: prodTesting99999
    alerting:
      name: prodTesting99999
      labels:
        category: Availability
      annotations:
        summary: prodTesting99999
      page_alert:
        labels:
          severity: critical
      ticket_alert:
        labels:
          severity: warning
