version: prometheus/v1
service: prod1
labels:
  product_id: eef
  env: stage
  org_id: TSE
slos:
  - name: slo1
    objective: 80
    description: slo1Desc
    sli:
      events:
        error_query: slo1EQ
        total_query: slo1TQ
    alerting:
      name: slo1AlertAnnot1
      labels:
        category: Availability
      annotations:
        summary: slo1AlerANoot1
      page_alert:
        labels:
          severity: critical
      ticket_alert:
        labels:
          severity: warning
